main: me.noodles.gui.main.Main
name: LiteBansGUI
version: 1.7
author: BGHDDevelopment
website: https://bghddevelopment.com
description: A GUI plugin that connects to LiteBans.
commands:
   punish:
      description: /punish (player)
   litebansgui:
      description: Information about LiteBansGUI