name: LiteBansGUI
version: ${project.version}
main: me.noodles.gui.Main
authors: [BGHDDevelopment]
description: A GUI plugin that connects to LiteBans.
website: https://bghddevelopment.com
commands:
   punish:
      description: /punish (player).
   litebansgui:
      description: Information about LiteBansGUI.
   litebansguireload:
      description: Reloads config file.